# To build: docker build -t generalmeow/mysharesconsumer:<TAG>-arm .
# To run: docker run generalmeow/mysharesconsumer:<TAG>-arm --spring.config.name=<ENV> <DBPROFILE> ... ENV application/dev/prod, EBPROFILE=mongodb/rethinkdb/influxdb
# i.e docker run generalmeow/mysharesconsumer:<TAG>-arm --spring.config.name=dev rethinkdb
FROM larmog/armhf-alpine-java:jdk-8u73
MAINTAINER Paul Hoang 2017-01-05
RUN ["mkdir", "-p", "/home/javaapp"]
WORKDIR /home/javaapp
COPY ./build/libs/mySharesConsumer-1.4.jar /home/javaapp/mySharesConsumer.jar
ENTRYPOINT ["java", "-jar", "mySharesConsumer.jar"]
